#!/bin/bash -e

ENV="$1"

if [ -z "$ENV" ]; then
    echo usage: $0 /etc/environment
    exit 1
fi

# just wait for interfaces to be ready
ifaces=`ifconfig | grep ens3 | cut -f1 -d: | tr "\n" " "`
while [ -z "$ifaces" ]; do
    sleep 0.1
    ifaces=`ifconfig | grep ens3 | cut -f1 -d: | tr "\n" " "`
done

# just block until the second interface is ready
ipaddr=`ifconfig ${ifaces} | grep 'inet ' | sed 's/^ *//' | cut -f 2 -d ' '`
while [ -z "$ipaddr" ]; do
    sleep 0.1
    ifaces=`ifconfig | grep ${ifaces} | cut -f1 -d: | tr "\n" " "`
    ifaces=($ifaces)
    ipaddr=`ifconfig ${ifaces} | grep 'inet ' | sed 's/^ *//' | cut -f 2 -d ' '`
done

sed -i -e '/^COREOS_PUBLIC_IPV4=/d' \
    -e '/^COREOS_PRIVATE_IPV4=/d' \
    "${ENV}"

echo "COREOS_PUBLIC_IPV4=${ipaddr}" >> $ENV
echo "COREOS_PRIVATE_IPV4=127.0.0.1" >> $ENV
